### PR TITLE
Make slightly easier

### PR DESCRIPTION
**Pull request by cooljeanius**
This is based off of cooljeanius/wesnoth_mods#5 and is meant to close it. Most of my cheating in this campaign was actually just with debug mode, rather than editing the scenario files, so I don't actually have that many changes to make here, just a few near the start. I might do another playthru later where I actually edit stuff more, though.

### CODE REVIEW

**Comment by nemaara** [comment]
Are you editing these numbers in the first scenario because they're genuinely too hard, or just because? I'd like to see a replay too.

**Comment by nemaara** [comment]
Also editing the turn counter in S5 can be counterproductive, it might mean that you need to survive for longer instead of giving you a breather, so I wouldn't do that either.

**Comment by cooljeanius** [comment]
> Are you editing these numbers in the first scenario because they're genuinely too hard, or just because? I'd like to see a replay too.

All of the scenarios are genuinely too hard; I mostly only just edited the first one because I hadn't started fully relying on debug mode yet. Anyways, here's my replay from when I did actually manage to beat it:
[Gns-1-Ash replay.gz](https://github.com/nemaara/Genesis/files/7654991/Gns-1-Ash.replay.gz)
Note that it's from Wesnoth 1.14; I didn't save the ones from when I died due to wesnoth/wesnoth#6070

**Comment by nemaara** [comment]
Okay go ahead and make this an issue instead of a PR, I'll take a look at lowering the difficulty of easy and normal.

**Pull request closed without merging**
